# Welcome to Serverless!

service: deeplens-doorman-backend

provider:
  name: aws
  runtime: python3.7

  region: ap-northeast-1

  # you can overwrite defaults here
  stage: demo

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:SearchFacesByImage"
        - "rekognition:IndexFaces"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"

  # you can define service wide environment variables here
  environment:
    AWSREGION: ${env:AWSREGION}
    BUCKET_NAME: ${env:BUCKET_NAME}
    SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
    SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
    REKOGNITION_COLLECTION_ID: ${env:REKOGNITION_COLLECTION_ID}

functions:
  guess:
    handler: handler.guess
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
  unknown:
    handler: handler.unknown
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: unknown/
  train:
    handler: handler.train
    events:
      - http:
          path: faces/train
          method: post

plugins:
  - serverless-python-requirements
